### ISSUE TITLE
Doesn't RotateSH need some sign flips in sh1?

### ISSUE THREAD

**Issue by aras-p** [andrewwillmott/sh-lib#1]
I've been testing RotateSH function for rotating spherical harmonics in gaussian splatting content. And as far as I can tell, the `sh1` in `RotateSH` function needs some sign flips to work correctly, i.e. it should be like
```
    #ifdef VL_ROW_ORIENT
        // for row vectors, v' = v M
        float sh1[3][3] =
        {
            orient(1, 1), -orient(2, 1), orient(0, 1),
            -orient(1, 2), orient(2, 2), -orient(0, 2),
            orient(1, 0), -orient(2, 0), orient(0, 0)
        };
    #else
        // for column vectors, v' = M v
        float sh1[3][3] =
        {
            orient(1, 1), -orient(1, 2), orient(1, 0),
            -orient(2, 1), orient(2, 2), -orient(2, 0),
            orient(0, 1), -orient(0, 2), orient(0, 0)
        };
    #endif
```
Is my understanding wrong, or does that depend on some other factors like coordinate axes conventions etc.?

**Comment by andrewwillmott** [comment]
Huh. 

So I _think_ it's correct as is according to my understanding, so presumably this must be a coordinate system thing. Because the corresponding band 1 basis functions are x/y/z, the rotation matrix applies directly to them, except that, in spherical harmonics they're ordered y, z, x. (Presumably to keep 'z' as the zonal harmonics axis.) Hence 'orient' being permuted yzx in row and column to construct the corresponding basis rotation matrix.

One thing that's worth checking is that the SH basis functions are the same on your side -- the polynomials are given next to the kSH_Y_lm constants.

If I recall Unity is left-handed, whereas this code does assume a right-handed coordinate system. If I look at your sign flips, I think they're effectively negating the z axis, so that could be it? It's basically forming the SH rotation as Pt R P, where R is the passed-in rotation, and P is both permuting yzx -> xyz and negating z.

I'm going to go and actually double-check the code's working, but I'll post this now in case that's it. I'm working on pushing my current version of this library too, after your comment the other day reminded me I'd not updated the public version in forever :)

**Comment by andrewwillmott** [comment]
Okay, everything seems to be in order. The euler angles here are relative to X-forward, Y-left, Z-up (right handed), so roll rotates ccw about +X, then pitch +Y, then heading +Z.

https://github.com/andrewwillmott/sh-lib/assets/4959327/aad22890-4852-4c78-92f9-4542ebd167eb

As a thought, I think you could convert the SH coefficients to be left handed by doing the equivalent of `MirrorSHInZ`, i.e., negating every term where `l + m` is odd. Which come to think of it is what your changes above do.

**Comment by aras-p** [comment]
Ah, got it, thanks for the double check and the explanation!
